### ISSUE TITLE
What do we want to do with this site?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desihub.github.io#1]
This site has not been updated in approximately four years. Perhaps we will find a use for this site in the future, but for now, if you visit https://github.com/desihub, the *link* associated with the DESI project is http://desihub.github.io.  Do we want to continue to have people interested in DESI code visit that out-of-date site?

**Comment by sbailey** [comment]
Thanks for noticing this.  It is out of date, but also outlines the packages in a clean, concise way that isn't well represented by any of our other public or private pages.  I suggest that we
* update it to be correct (e.g. replacing redmonster with redrock)
* keep it minimalist enough that it won't get out-of-date too fast
* include a link to desi.lbl.gov

**Comment by weaverba137** [comment]
@sbailey, this package/site has now been untouched for about *eight years*. I think we should remove it, or just replace the existing site with a stub site that links to our actively updated documentation pages.

**Comment by sbailey** [comment]
Fine to remove it or replace with a stub site with a link to https://data.desi.lbl.gov/doc

**Comment by weaverba137** [comment]
Done!
