### ISSUE TITLE
Source code for desihub.github.io?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desihub.github.io#2]
@dkirkby, when you created this site, did you write it by hand, or use some form of HTML generator?  If the latter, can we get that source code?

**Comment by dkirkby** [comment]
I created it using the github automatic page creator tool (as of 2015).  I believe @sbailey later added the list of packages.

**Comment by sbailey** [comment]
The video at https://pages.github.com refers to a "automatic page generator" on the settings tab that no longer seems to exist.  IIRC we used to be able to edit pages in markdown similar to issues/ PRs / comments, and github would turn that into html.  I don't see how to do that anymore.

**Comment by weaverba137** [comment]
OK, I think we'll just edit the HTML by hand for now.  What about the packages.png file?  We will need to regenerate that since it still mentions redmonster.

**Comment by weaverba137** [comment]
Based on some old email threads, it looks like the packages.png file was created in Graffle. Unfortunately, that is not free & open-source software. Also, it was not clear who actually created that file, although it seems likely that it was either @sbailey or @dkirkby.  Maybe that figure should be recreated in SVG with something like [InkScape](https://inkscape.org/).

**Comment by weaverba137** [comment]
There is no longer any need to get the source code for this site.
